<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '978-0-7432-7356-5',
                'category' => 'Fiction',
                'publisher' => 'Scribner',
                'publication_year' => 1925,
                'description' => 'A classic American novel about the Jazz Age and the decline of the American Dream.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book1.jpg',
                'popularity' => 95,
                'rent_fee' => 50.00,
                'deposit' => 200.00,
                'quantity' => 5,
                'available_quantity' => 3,
                'status' => 'available',
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '978-0-452-28423-4',
                'category' => 'Science Fiction',
                'publisher' => 'Signet Classic',
                'publication_year' => 1949,
                'description' => 'A dystopian social science fiction novel about totalitarian surveillance.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book2.jpg',
                'popularity' => 88,
                'rent_fee' => 45.00,
                'deposit' => 180.00,
                'quantity' => 4,
                'available_quantity' => 2,
                'status' => 'available',
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '978-0-06-112008-4',
                'category' => 'Fiction',
                'publisher' => 'HarperCollins',
                'publication_year' => 1960,
                'description' => 'A gripping tale of racial injustice and childhood innocence in the American South.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book3.jpg',
                'popularity' => 92,
                'rent_fee' => 55.00,
                'deposit' => 220.00,
                'quantity' => 6,
                'available_quantity' => 4,
                'status' => 'available',
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'isbn' => '978-0-14-143951-8',
                'category' => 'Fiction',
                'publisher' => 'Penguin Classics',
                'publication_year' => 1813,
                'description' => 'A romantic novel of manners that critiques the British landed gentry.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book1.jpg',
                'popularity' => 85,
                'rent_fee' => 48.00,
                'deposit' => 190.00,
                'quantity' => 3,
                'available_quantity' => 1,
                'status' => 'available',
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'isbn' => '978-0-316-76948-0',
                'category' => 'Fiction',
                'publisher' => 'Little, Brown and Company',
                'publication_year' => 1951,
                'description' => 'A controversial novel about teenage rebellion and alienation.',
                'language' => 'English',
                'condition' => 'fair',
                'image' => 'images/book2.jpg',
                'popularity' => 78,
                'rent_fee' => 42.00,
                'deposit' => 170.00,
                'quantity' => 4,
                'available_quantity' => 2,
                'status' => 'available',
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'isbn' => '978-0-06-231609-7',
                'category' => 'History',
                'publisher' => 'Harper',
                'publication_year' => 2014,
                'description' => 'An exploration of how Homo sapiens came to dominate the world.',
                'language' => 'English',
                'condition' => 'new',
                'image' => 'images/book3.jpg',
                'popularity' => 90,
                'rent_fee' => 60.00,
                'deposit' => 250.00,
                'quantity' => 5,
                'available_quantity' => 3,
                'status' => 'available',
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'isbn' => '978-0-439-02348-1',
                'category' => 'Science Fiction',
                'publisher' => 'Scholastic',
                'publication_year' => 2008,
                'description' => 'A dystopian novel about a televised fight to the death.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book1.jpg',
                'popularity' => 82,
                'rent_fee' => 52.00,
                'deposit' => 210.00,
                'quantity' => 7,
                'available_quantity' => 5,
                'status' => 'available',
            ],
            [
                'title' => 'The Lord of the Rings',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '978-0-544-00014-8',
                'category' => 'Fantasy',
                'publisher' => 'Houghton Mifflin',
                'publication_year' => 1954,
                'description' => 'An epic high fantasy novel about the quest to destroy the One Ring.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book2.jpg',
                'popularity' => 96,
                'rent_fee' => 65.00,
                'deposit' => 280.00,
                'quantity' => 4,
                'available_quantity' => 1,
                'status' => 'available',
            ],
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'isbn' => '978-0-7475-3269-6',
                'category' => 'Fantasy',
                'publisher' => 'Bloomsbury',
                'publication_year' => 1997,
                'description' => 'The first book in the Harry Potter series about a young wizard.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book3.jpg',
                'popularity' => 98,
                'rent_fee' => 58.00,
                'deposit' => 240.00,
                'quantity' => 8,
                'available_quantity' => 2,
                'status' => 'available',
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'isbn' => '978-0-06-112241-5',
                'category' => 'Fiction',
                'publisher' => 'HarperOne',
                'publication_year' => 1988,
                'description' => 'A philosophical novel about a young Andalusian shepherd on a journey.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book1.jpg',
                'popularity' => 80,
                'rent_fee' => 50.00,
                'deposit' => 200.00,
                'quantity' => 5,
                'available_quantity' => 3,
                'status' => 'available',
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'isbn' => '978-0-553-10953-5',
                'category' => 'Science',
                'publisher' => 'Bantam Books',
                'publication_year' => 1988,
                'description' => 'A popular science book about cosmology and theoretical physics.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book2.jpg',
                'popularity' => 75,
                'rent_fee' => 55.00,
                'deposit' => 220.00,
                'quantity' => 3,
                'available_quantity' => 1,
                'status' => 'available',
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'isbn' => '978-0-385-50420-5',
                'category' => 'Mystery',
                'publisher' => 'Doubleday',
                'publication_year' => 2003,
                'description' => 'A mystery thriller novel about a conspiracy within the Catholic Church.',
                'language' => 'English',
                'condition' => 'good',
                'image' => 'images/book3.jpg',
                'popularity' => 72,
                'rent_fee' => 48.00,
                'deposit' => 190.00,
                'quantity' => 6,
                'available_quantity' => 4,
                'status' => 'available',
            ],
        ];

        foreach ($books as $book) {
            try {
                Book::firstOrCreate(
                    ['isbn' => $book['isbn']],
                    array_merge($book, [
                        'created_at' => now(),
                        'updated_at' => now(),
                    ])
                );
            } catch (\Exception $e) {
                // If ISBN is null or duplicate, try creating without ISBN check
                Book::create(array_merge($book, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }
}
